### ISSUE TITLE
error when install demo

### ISSUE THREAD

**Issue by cooliobr** [immstudios/nebula-demo#2]
```
Starting database server

Creating network "nebulademo_default" with the default driver
Creating volume "nebulademo_database" with default driver
Creating nebulademo_postgres_1 ... 
Creating nebulademo_postgres_1 ... done
Waiting for PostgreSQL
Waiting for PostgreSQL
Waiting for PostgreSQL
Waiting for PostgreSQL
Waiting for PostgreSQL
Waiting for PostgreSQL

Creating the database and user


Creating database schema

psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "nebula" does not exist

Applying site settings

Creating nebulademo_memcached_1 ... 
Starting nebulademo_postgres_1 ... 
Starting nebulademo_postgres_1 ... done
Creating nebulademo_memcached_1
Creating nebulademo_rabbitmq_1 ... done
2022-02-19 14:44:13 INFO       Installing site settings
Traceback (most recent call last):
  File "/opt/nebula-setup/./setup.py", line 285, in <module>
    install_settings()
  File "/opt/nebula-setup/./setup.py", line 119, in install_settings
    db = DB()
  File "/opt/nebula-setup/./setup.py", line 85, in __init__
    self.conn = psycopg2.connect(**self.settings)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "nebula"


Installation completed

Now run 'docker-compose up' or 'docker-compose up -d' to bring your stack to life
```

**Comment by martastain** [comment]
Hello, I've fixed the installation script and also created new base docker image. Please update the repo and remove nebula image using `docker rmi nebulabroadcast/nebula-base` before running install.sh again. Feel free to reopen the issue if the problem persists.

**Comment by cooliobr** [comment]
Sorry, it don't work, may I do any wrong.
i do clone from git again but keep same problem.

i sent email to buy some tech help to install this project.
